import Game from game
        def get_user_menu_choice():
        



        
#             item = ("Menu: ", "Play a new game", "Show scores", "Quit")
#                     print item
#                     - show the user menu,

#             - print_results(results)
#         - print the results

# def main():
# def get_user_menu_choice() --> continue asking until the user
#         entered a valid choice

#         # - create a game object and call the play() method
#         Game(play())